<?php

namespace Tests\Feature;

use App\Models\Product;
use App\Models\Store;
use App\Support\Media;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * What a video costs to serve.
 *
 * A clip is the most expensive thing a shop can put on a page, and the bill
 * lands on the host it is served from. Three things keep it in hand: a poster
 * so nothing is fetched until someone presses play, a cap on the source, and
 * one setting that moves every upload to a bucket when the shared host stops
 * being the right place for it.
 */
class MediaDeliveryCostTest extends TestCase
{
    use RefreshDatabase;

    private Store $store;

    protected function setUp(): void
    {
        parent::setUp();
        $this->seedPlatform();
        Storage::fake('public');

        $this->store = $this->makeStore();
        $this->store->forceFill(['is_published' => true])->save();
    }

    private function submit(array $extra): \Illuminate\Testing\TestResponse
    {
        return $this->actingAs($this->store->owner)->post('/dashboard/produk', array_merge([
            'type' => 'PHYSICAL',
            'name' => 'Piyama Busui',
            'price' => 110000,
            'status' => 'DRAFT',
            'visibility' => 'public',
            'initial_stock' => 5,
            'weight_gram' => 500,
            'length_cm' => 20,
            'width_cm' => 15,
            'height_cm' => 5,
        ], $extra));
    }

    public function test_a_video_keeps_the_poster_captured_beside_it(): void
    {
        $this->submit([
            'gallery' => [UploadedFile::fake()->create('pakai.mp4', 2048, 'video/mp4')],
            'gallery_posters' => ['0' => UploadedFile::fake()->image('poster.jpg')],
        ])->assertSessionHasNoErrors()->assertRedirect();

        $media = Product::firstOrFail()->media()->firstOrFail();

        $this->assertSame('video', $media->kind);
        $this->assertNotNull($media->poster_path, 'Tanpa poster, tiap pengunjung mengunduh videonya.');
        Storage::disk('public')->assertExists($media->poster_path);
    }

    public function test_the_storefront_hands_the_poster_to_the_page(): void
    {
        $product = $this->makeProduct($this->store);
        $product->media()->create([
            'path' => 'products/gallery/a.mp4',
            'kind' => 'video',
            'poster_path' => 'products/posters/a.jpg',
            'position' => 1,
        ]);

        $this->get("/{$this->store->username}/p/{$product->slug}")
            ->assertOk()
            ->assertInertia(fn ($page) => $page->where('product.media.0.poster', '/storage/products/posters/a.jpg'));
    }

    public function test_a_poster_is_only_accepted_as_a_small_image(): void
    {
        // The poster is generated by the browser, which means the field is as
        // reachable as any other — it is not a second video upload slot.
        $this->submit([
            'gallery' => [UploadedFile::fake()->create('pakai.mp4', 1024, 'video/mp4')],
            'gallery_posters' => ['0' => UploadedFile::fake()->create('sneaky.jpg', 5000, 'video/mp4')],
        ])->assertSessionHasErrors('gallery_posters.0');

        $this->assertSame(0, Product::count());
    }

    public function test_the_video_cap_is_the_configured_one(): void
    {
        $this->assertSame(25600, (int) config('jualanyok.uploads.video_max_kb'));

        $this->submit([
            'gallery' => [UploadedFile::fake()->create('panjang.mp4', 30 * 1024, 'video/mp4')],
        ])->assertSessionHasErrors();

        $this->assertSame(0, Product::count());
    }

    public function test_deleting_a_video_takes_its_poster_with_it(): void
    {
        $this->submit([
            'gallery' => [UploadedFile::fake()->create('pakai.mp4', 1024, 'video/mp4')],
            'gallery_posters' => ['0' => UploadedFile::fake()->image('poster.jpg')],
        ])->assertSessionHasNoErrors();

        $product = Product::firstOrFail();
        $media = $product->media()->firstOrFail();

        $this->actingAs($this->store->owner)->put("/dashboard/produk/{$product->id}", [
            '_method' => 'put',
            'type' => 'PHYSICAL',
            'name' => $product->name,
            'price' => 110000,
            'status' => 'DRAFT',
            'visibility' => 'public',
            'weight_gram' => 500,
            'length_cm' => 20,
            'width_cm' => 15,
            'height_cm' => 5,
            'removed_media_ids' => [$media->id],
        ])->assertSessionHasNoErrors();

        // An orphaned poster is a file nobody will ever look for again.
        Storage::disk('public')->assertMissing($media->path);
        Storage::disk('public')->assertMissing($media->poster_path);
    }

    public function test_moving_media_to_a_bucket_is_one_setting(): void
    {
        // Nothing in the app writes to a disk of its own choosing, so pointing
        // this elsewhere moves every upload path at once.
        Storage::fake('s3');
        config(['jualanyok.uploads.disk' => 's3']);

        $this->submit([
            'gallery' => [UploadedFile::fake()->image('depan.jpg')],
        ])->assertSessionHasNoErrors();

        $path = Product::firstOrFail()->media()->value('path');

        Storage::disk('s3')->assertExists($path);
        Storage::disk('public')->assertMissing($path);
    }

    public function test_a_local_url_stays_root_relative(): void
    {
        // Baking the current host into stored media is how every image breaks
        // the day the app gains a custom domain.
        $this->assertSame('/storage/products/gallery/a.jpg', Media::url('products/gallery/a.jpg'));
        $this->assertNull(Media::url(null));
    }
}
