import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, ArrowUpRight, BadgeCheck, Check, Heart, PackageCheck, Share2, ShieldCheck, ShoppingBag } from 'lucide-react';
import { useState } from 'react';
import ProductCard, { type MarketplaceProduct } from '@/components/marketplace/ProductCard';
import MarketingLayout from '@/layouts/MarketingLayout';
import { cn, formatIDR } from '@/lib/utils';

interface ProductDetail extends MarketplaceProduct { description: string | null; terms: string | null; media: { url: string; alt: string }[]; variants: any[]; is_buyable: boolean; storefront_url: string; refund_policy_url: string }

export default function ProductPage({ product, moreFromCreator, similarProducts }: { product: ProductDetail; moreFromCreator: MarketplaceProduct[]; similarProducts: MarketplaceProduct[] }) {
    const [activeImage, setActiveImage] = useState(product.media[0]?.url ?? product.thumbnail_url);
    const [wished, setWished] = useState(false);
    const share = async () => { const data = { title: product.name, text: product.short_description ?? product.name, url: window.location.href }; if (navigator.share) await navigator.share(data); else await navigator.clipboard.writeText(window.location.href); };

    return <MarketingLayout title={product.name} description={product.short_description ?? `Produk dari ${product.store.name}`}>
        <Head><link rel="canonical" href={product.url} /><meta property="og:type" content="product" /><meta property="og:title" content={product.name} />{product.thumbnail_url && <meta property="og:image" content={product.thumbnail_url} />}<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'Product', name: product.name, image: [product.thumbnail_url, ...product.media.map((item) => item.url)].filter(Boolean), description: product.short_description, offers: product.type !== 'EXTERNAL' ? { '@type': 'Offer', priceCurrency: 'IDR', price: product.price, availability: product.is_buyable ? 'https://schema.org/InStock' : 'https://schema.org/OutOfStock', url: product.url } : undefined, brand: { '@type': 'Brand', name: product.store.name } }) }} /></Head>
        <div className="mx-auto max-w-6xl px-4 pb-28 pt-5 sm:px-6 sm:pt-10"><Link href="/explore" className="inline-flex items-center gap-2 text-xs font-bold text-neutral-500 hover:text-violet-700"><ArrowLeft className="size-4" /> Kembali jelajah</Link><div className="mt-5 grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:gap-14">
            <div><div className="aspect-square overflow-hidden rounded-[1.75rem] border border-line bg-[#f4f0fa]">{activeImage ? <img src={activeImage} alt={product.name} className="size-full object-cover" /> : <div className="grid size-full place-items-center"><ShoppingBag className="size-16 text-violet-300" /></div>}</div>{product.media.length > 0 && <div className="mt-3 flex gap-2 overflow-x-auto">{[product.thumbnail_url, ...product.media.map((item) => item.url)].filter(Boolean).map((url) => <button key={url!} onClick={() => setActiveImage(url!)} className={cn('size-16 shrink-0 overflow-hidden rounded-xl border-2', activeImage === url ? 'border-violet-600' : 'border-transparent')}><img src={url!} alt="" className="size-full object-cover" /></button>)}</div>}</div>
            <div className="lg:pt-3"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-violet-100 px-3 py-1 text-[10px] font-extrabold text-violet-700">{product.type_label}</span>{product.affiliate_enabled && <span className="rounded-full bg-amber-100 px-3 py-1 text-[10px] font-extrabold text-amber-800">Affiliate tersedia</span>}</div><h1 className="mt-5 text-3xl font-black leading-[1.12] tracking-[-.045em] sm:text-5xl">{product.name}</h1>{product.short_description && <p className="mt-4 text-sm leading-7 text-neutral-600 sm:text-base">{product.short_description}</p>}
                <Link href={product.store.url} className="mt-6 flex items-center gap-3 rounded-2xl border border-line p-3 transition hover:border-violet-200 hover:bg-violet-50/50"><span className="grid size-11 place-items-center overflow-hidden rounded-full bg-violet-100 font-black text-violet-700">{product.store.avatar_url ? <img src={product.store.avatar_url} alt="" className="size-full object-cover" /> : product.store.name.charAt(0)}</span><div className="min-w-0"><p className="flex items-center gap-1.5 text-sm font-extrabold">{product.store.name}{product.store.is_verified && <BadgeCheck className="size-4 fill-violet-600 text-white" />}</p><p className="text-[11px] text-neutral-500">@{product.store.username}</p></div></Link>
                <div className="mt-7 rounded-[1.5rem] border border-black/[.07] bg-white p-5 shadow-[0_16px_45px_rgba(40,28,80,.08)]"><div className="flex items-end justify-between gap-3"><div>{product.compare_at_price && <p className="text-xs text-neutral-400 line-through">{formatIDR(product.compare_at_price)}</p>}<p className="text-3xl font-black tracking-tight">{product.type === 'EXTERNAL' ? 'Cek harga terbaru' : product.price === 0 ? 'Gratis' : formatIDR(product.price)}</p></div>{product.sales_count > 0 && <p className="text-xs font-bold text-neutral-400">{product.sales_count.toLocaleString('id-ID')} terjual</p>}</div>
                    <div className="mt-5 grid grid-cols-[1fr_auto_auto] gap-2"><Link href={product.storefront_url} className="flex h-12 items-center justify-center gap-2 rounded-full bg-[#171722] px-4 text-xs font-extrabold text-white hover:bg-violet-700">{product.type === 'EXTERNAL' ? `Buka ${product.external_provider ?? 'marketplace'}` : 'Pilih & beli di toko'}{product.type === 'EXTERNAL' ? <ArrowUpRight className="size-4" /> : <ShoppingBag className="size-4" />}</Link><button onClick={() => setWished((v) => !v)} className="grid size-12 place-items-center rounded-full border border-line" aria-label="Favorit"><Heart className={cn('size-4', wished && 'fill-rose-500 text-rose-500')} /></button><button onClick={share} className="grid size-12 place-items-center rounded-full border border-line" aria-label="Bagikan"><Share2 className="size-4" /></button></div>
                    <div className="mt-5 grid gap-3 border-t border-line pt-5 text-[11px] font-semibold text-neutral-600 sm:grid-cols-2"><span className="flex gap-2"><ShieldCheck className="size-4 text-emerald-600" /> Pembayaran provider resmi</span><span className="flex gap-2"><PackageCheck className="size-4 text-violet-600" /> Delivery sesuai jenis produk</span></div>
                </div>
            </div>
        </div>
        <div className="mt-14 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-[1.5rem] border border-line bg-white p-6 sm:p-8"><h2 className="text-xl font-black">Tentang produk</h2><div className="mt-5 whitespace-pre-line text-sm leading-8 text-neutral-600">{product.description || product.short_description || 'Creator belum menambahkan deskripsi lengkap.'}</div></section><aside className="rounded-[1.5rem] border border-line bg-[#f8f6fb] p-6"><h2 className="text-sm font-black">Belanja dengan tenang</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-neutral-600"><li className="flex gap-2"><Check className="size-4 shrink-0 text-emerald-600" /> Transaksi diproses melalui alur checkout JualanYok.</li><li className="flex gap-2"><Check className="size-4 shrink-0 text-emerald-600" /> Produk digital dikirim otomatis setelah pembayaran valid.</li><li className="flex gap-2"><Check className="size-4 shrink-0 text-emerald-600" /> Produk fisik mengikuti tracking dan kebijakan komplain.</li></ul><Link href={product.refund_policy_url} className="mt-5 inline-flex text-xs font-extrabold text-violet-700">Baca kebijakan refund</Link></aside></div>
        <ProductRow title={`Produk lain dari ${product.store.name}`} products={moreFromCreator} /><ProductRow title="Mungkin kamu juga suka" products={similarProducts} />
        </div>
        <div className="fixed bottom-0 left-0 right-0 z-40 border-t border-line bg-white/95 p-3 backdrop-blur lg:hidden"><div className="mx-auto flex max-w-lg items-center gap-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{product.name}</p><p className="text-sm font-black">{product.type === 'EXTERNAL' ? 'Cek harga' : formatIDR(product.price)}</p></div><Link href={product.storefront_url} className="flex h-11 items-center rounded-full bg-[#171722] px-5 text-xs font-extrabold text-white">Lanjut beli</Link></div></div>
    </MarketingLayout>;
}

function ProductRow({ title, products }: { title: string; products: MarketplaceProduct[] }) { if (!products.length) return null; return <section className="mt-16"><div className="flex items-end justify-between"><h2 className="text-2xl font-black tracking-tight">{title}</h2><Link href="/explore" className="text-xs font-extrabold text-violet-700">Lihat semua</Link></div><div className="mt-6 grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-4">{products.map((product) => <ProductCard key={product.id} product={product} compact />)}</div></section>; }
